language: python
python:
- '3.4'
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- '3.7'
os:
- linux
script:
- pip install setuptools
- python setup.py check
- python setup.py test
jobs:
  include:
  - stage: deploy pypi
    python: 3.7
    script: true
    before_deploy:
    - rm -rf ./build
    - rm -rf ./dist
    - pip install setuptools
    - python setup.py sdist build
    deploy:
      provider: pypi
      user: Mryan
      password: "${password}"
      skip_cleanup: true
      on:
        python: 3.7
        tags: true
  - stage: deploy GitHub
    python: 3.7
    script: true
    before_deploy:
    - rm -rf ./build
    - rm -rf ./dist
    - pip install setuptools
    - python setup.py sdist build
    deploy:
      provider: releases
      api_key:
        secure: nA509nJv4jh0v1e57p2KzbY2bXJCpe8dx9HInxKR3WWunYq8GbNTjdc1TXPUpX290oadvoutxAfBX1H229JktC84BUyTxvRLvof4c2nT68Yzqdivz24CA3px1q8UhWtbHHYWJA7EhHdVuFq6tI/Ug5UxwbJCmTtTgFEycBHeYoDf1YEc7AZcbd6eJ69kzNe7vB6xim5qiHYuYPhjd95SSiRG2g7xoOoNNaoXYdGfNpxytElJbPW1QdNBVlWB8DlRVf1nmuRiHvMu/6EwO7bhWqArvZZM0mYcHLt2Hxs/jcbGTIXuckN5Ndo70Z+ti2NG7AQFQtkiLt5OmGgr3WU26rwn0hNgWc6T3PsMLiyXqo6qJdq6/XpD435zvwjLaXAvqcXxx80oq522sZVWsBej7v35tD8YZL+3M+SjffTVPqBMFh/rDKsAf/oSEcfQZdpa910j3B5Q4dDftgjfsw7LU/Jc1LRS4d5q0J5x7TagYZ0z0OWiWsB1bFR1NlrXdn4eXihfCvp4uytvDWlmwO76d1KUgOr6GxIHowIAv8f7LJG+uiNcORVel95//X0RTZm+G2PvRW+iwJD7/VE9Uk2qgLtQJlmB8y3tuyO7wwQRzKS3ICw6K3a3iaPO6PwLzMjMyrtPbkBx93kyxW3NmtPN0SsM5viYRvlzzAZY3J06dm4=
      file: "./dist/*.tar.gz"
      on:
        python: 3.7
        tags: true
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=bff998e4df4150d1c627438c992459b1a5542f37217f11ba2bea01adfe829f7a

