language: python
python:
- '3.4'
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- '3.7'
os:
- linux
jobs:
  include:
    - stage: test
      script: pip install setuptools
      script: python setup.py check
      script: python setup.py test
    - stage: deploy GitHub
      python: '3.7'
      script: pip install setuptools
      script: python setup.py sdist build
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
    - stage: deploy Pypi
      python: '3.7'
      script: rm -rf ./build
      script: rm -rf ./dist
      script: pip install setuptools
      script: python setup.py sdist build
      deploy:
        provider: pypi
        user: Mryan
        password: ${password}
        skip_cleanup: true
        on:
          tags: true
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=bff998e4df4150d1c627438c992459b1a5542f37217f11ba2bea01adfe829f7a
